### ISSUE TITLE
初次启动报错

### ISSUE THREAD

**Issue by shangxueink** [Alin-sky/koishi-plugin-ba-plugin#21]

**Comment by shangxueink** [comment]
```
2024-10-19 21:20:55 [I] canvas canvas started
2024-10-19 21:21:04 [I] loader apply plugin ba-plugin:d5ny4c
2024-10-19 21:21:04 [I] ba-plugin 渲染模式:canvas
2024-10-19 21:21:04 [I] ba-plugin-FMPS 尝试读取C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\data\bap-json/hash.json失败，尝试次数：1
2024-10-19 21:21:04 [I] ba-plugin-FMPS 尝试读取C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\data\bap-json/hash.json失败，尝试次数：2
2024-10-19 21:21:05 [I] ba-plugin-FMPS 尝试读取C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\data\bap-json/hash.json失败，尝试次数：3
2024-10-19 21:21:05 [I] ba-plugin-FMPS 尝试3次后依旧报错，停止尝试
2024-10-19 21:21:09 [I] ba-plugin 🟡 正在更新json文件
2024-10-19 21:21:09 [I] ba-plugin ☁️🆕🟡云hash更新
2024-10-19 21:21:12 [E] ba-plugin TypeError: Cannot read properties of undefined (reading 'fname')
                            at file_random_survey (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-ba-plugin\lib\index.js:7110:60)
                            at async initia (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-ba-plugin\lib\index.js:7230:14)
                            at async auto_data_update_function (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-ba-plugin\lib\index.js:7306:5)
                            at async Object.apply (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-ba-plugin\lib\index.js:7310:5)
2024-10-19 21:21:12 [I] ba-plugin 🟡本地资源检测未通过
2024-10-19 21:21:12 [I] ba-plugin ⬇️ 开始下载插件必须资源，请稍等哦（*＾-＾*）
2024-10-19 21:21:20 [I] ba-plugin 头像_1下载进度25%
2024-10-19 21:21:20 [I] ba-plugin 头像_1下载进度25%
2024-10-19 21:21:27 [I] ba-plugin 头像_1下载进度50%
2024-10-19 21:21:27 [I] ba-plugin 头像_1下载进度50%
2024-10-19 21:21:35 [I] ba-plugin 头像_1下载进度75%
2024-10-19 21:21:35 [I] ba-plugin 头像_1下载进度75%
2024-10-19 21:21:41 [I] ba-plugin 头像_1下载进度95%
2024-10-19 21:21:41 [I] ba-plugin 头像_1下载进度95%
2024-10-19 21:21:42 [I] ba-plugin ✔️（1/3）学生头像_1下载完毕
2024-10-19 21:21:48 [I] ba-plugin 头像_2下载进度25%
2024-10-19 21:21:49 [I] ba-plugin 头像_2下载进度25%
2024-10-19 21:21:54 [I] ba-plugin 头像_2下载进度50%
2024-10-19 21:21:55 [I] ba-plugin 头像_2下载进度50%
2024-10-19 21:22:02 [I] ba-plugin 头像_2下载进度75%
2024-10-19 21:22:02 [I] ba-plugin 头像_2下载进度75%
2024-10-19 21:22:07 [I] ba-plugin 头像_2下载进度95%
2024-10-19 21:22:07 [I] ba-plugin 头像_2下载进度95%
2024-10-19 21:22:08 [I] ba-plugin ✔️（2/3）学生头像_2下载完毕
2024-10-19 21:22:11 [I] ba-plugin 资源文件下载进度25%
2024-10-19 21:22:14 [I] ba-plugin 资源文件下载进度50%
2024-10-19 21:22:18 [I] ba-plugin 资源文件下载进度75%
2024-10-19 21:22:25 [I] ba-plugin 资源文件下载进度95%
2024-10-19 21:22:26 [I] ba-plugin ✔️（3/3）资源下载完毕
2024-10-19 21:22:29 [I] ba-plugin 🟢 json文件更新完毕
2024-10-19 21:22:29 [I] ba-plugin-get-active ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:22:29 [I] ba-plugin-get-active 🟢 总力获取加载完毕
2024-10-19 21:22:29 [I] ba-plugin-get-active 🟢 活动获取功能加载完毕
2024-10-19 21:22:29 [I] ba-plugin-guide ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:22:29 [I] ba-plugin-favorable 🟢 好感计算器加载完毕
2024-10-19 21:22:29 [I] ba-plugin-guide 🟢 攻略功能加载完毕
2024-10-19 21:22:29 [I] ba-plugin-gacha ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:22:29 [I] ba-plugin-gacha 🟢 抽卡模拟器加载完毕
2024-10-19 21:22:29 [I] sqlite auto creating table bap_db
2024-10-19 21:22:29 [I] ba-plugin-gacha 🟢 随机漫画加载完毕
```


看起来是检查文件的逻辑与下载的逻辑  没配合好
