### ISSUE TITLE
文件下载完成，成功加载过，但是重启会导致报错重下资源

### ISSUE THREAD

**Issue by shangxueink** [Alin-sky/koishi-plugin-ba-plugin#22]
在koishi desktop下 
```
2024-10-19 21:24:35 [I] canvas canvas started
2024-10-19 21:24:35 [I] ba-plugin 渲染模式:canvas
2024-10-19 21:24:35 [I] ba-plugin 🟡 正在更新json文件
2024-10-19 21:24:35 [I] ba-plugin ☁️   🟢云hash未更新
2024-10-19 21:24:35 [I] ba-plugin-get-active ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:24:35 [I] ba-plugin-get-active 🟢 总力获取加载完毕
2024-10-19 21:24:35 [I] ba-plugin-get-active 🟢 活动获取功能加载完毕
2024-10-19 21:24:35 [I] ba-plugin-guide ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:24:35 [I] ba-plugin-guide 🟢 攻略功能加载完毕
2024-10-19 21:24:35 [I] ba-plugin-favorable 🟢 好感计算器加载完毕
2024-10-19 21:24:35 [I] ba-plugin-gacha ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:24:35 [I] ba-plugin-gacha 🟢 抽卡模拟器加载完毕
2024-10-19 21:24:35 [I] ba-plugin-gacha 🟢 随机漫画加载完毕
```
看起来一切正常呢

---

但是在项目模板下，我们从插件市场安装ba-p

```
2024-10-19 21:26:05 [I] loader apply plugin canvas:uvr7ds
2024-10-19 21:26:10 [I] loader apply plugin ba-plugin:g74ndf
2024-10-19 21:26:11 [I] canvas canvas started
2024-10-19 21:26:11 [I] ba-plugin 渲染模式:canvas
2024-10-19 21:26:11 [I] ba-plugin-FMPS 尝试读取D:\QQbots\QQ_bots\koishing\coding\koishi-app\data\bap-json/hash.json失败，尝试次数：1
2024-10-19 21:26:12 [I] ba-plugin-FMPS 尝试读取D:\QQbots\QQ_bots\koishing\coding\koishi-app\data\bap-json/hash.json失败，尝试次数：2
2024-10-19 21:26:12 [I] ba-plugin-FMPS 尝试读取D:\QQbots\QQ_bots\koishing\coding\koishi-app\data\bap-json/hash.json失败，尝试次数：3
2024-10-19 21:26:12 [I] ba-plugin-FMPS 尝试3次后依旧报错，停止尝试
2024-10-19 21:26:17 [I] ba-plugin 🟡 正在更新json文件
2024-10-19 21:26:17 [I] ba-plugin ☁️🆕🟡云hash更新
2024-10-19 21:26:20 [E] ba-plugin TypeError: Cannot read properties of undefined (reading 'fname')
                            at file_random_survey (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7110:60)
                            at async initia (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7230:14)
                            at async auto_data_update_function (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7306:5)
                            at async Object.apply (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7310:5)
2024-10-19 21:26:20 [I] ba-plugin 🟡本地资源检测未通过
2024-10-19 21:26:20 [I] ba-plugin ⬇️ 开始下载插件必须资源，请稍等哦（*＾-＾*）
2024-10-19 21:26:27 [I] ba-plugin 头像_1下载进度25%
2024-10-19 21:26:28 [I] ba-plugin 头像_1下载进度25%
2024-10-19 21:26:34 [I] ba-plugin 头像_1下载进度50%
2024-10-19 21:26:35 [I] ba-plugin 头像_1下载进度50%
2024-10-19 21:26:42 [I] ba-plugin 头像_1下载进度75%
2024-10-19 21:26:42 [I] ba-plugin 头像_1下载进度75%
2024-10-19 21:26:48 [I] ba-plugin 头像_1下载进度95%
2024-10-19 21:26:48 [I] ba-plugin 头像_1下载进度95%
2024-10-19 21:26:49 [I] ba-plugin ✔️（1/3）学生头像_1下载完毕
2024-10-19 21:26:54 [I] storeluna 同步成功: https://registry.koishi.chat/index.json
2024-10-19 21:26:56 [I] ba-plugin 头像_2下载进度25%
2024-10-19 21:26:57 [I] ba-plugin 头像_2下载进度25%
2024-10-19 21:27:02 [I] ba-plugin 头像_2下载进度50%
2024-10-19 21:27:02 [I] ba-plugin 头像_2下载进度50%
2024-10-19 21:27:08 [I] ba-plugin 头像_2下载进度75%
2024-10-19 21:27:09 [I] ba-plugin 头像_2下载进度75%
2024-10-19 21:27:14 [I] ba-plugin 头像_2下载进度95%
2024-10-19 21:27:14 [I] ba-plugin 头像_2下载进度95%
2024-10-19 21:27:15 [I] ba-plugin ✔️（2/3）学生头像_2下载完毕
2024-10-19 21:27:20 [I] ba-plugin 资源文件下载进度25%
2024-10-19 21:27:23 [I] ba-plugin 资源文件下载进度50%
2024-10-19 21:27:27 [I] ba-plugin 资源文件下载进度75%
2024-10-19 21:27:35 [I] ba-plugin 资源文件下载进度95%
2024-10-19 21:27:36 [I] ba-plugin ✔️（3/3）资源下载完毕
2024-10-19 21:27:39 [I] ba-plugin 🟢 json文件更新完毕
2024-10-19 21:27:39 [I] ba-plugin-get-active ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:27:39 [I] ba-plugin-get-active 🟢 总力获取加载完毕
2024-10-19 21:27:39 [I] ba-plugin-get-active 🟢 活动获取功能加载完毕
2024-10-19 21:27:39 [I] ba-plugin-guide ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:27:39 [I] ba-plugin-guide 🟢 攻略功能加载完毕
2024-10-19 21:27:39 [I] ba-plugin-favorable 🟢 好感计算器加载完毕
2024-10-19 21:27:39 [I] ba-plugin-gacha ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:27:39 [I] ba-plugin-gacha 🟢 抽卡模拟器加载完毕
2024-10-19 21:27:39 [I] sqlite auto creating table bap_db
2024-10-19 21:27:39 [I] ba-plugin-gacha 🟢 随机漫画加载完毕

```

然后【关闭 重下资源的配置项】重启koishi

```
2024-10-19 21:30:26 [I] loader apply plugin ba-plugin:g74ndf
2024-10-19 21:30:26 [I] loader apply plugin canvas:uvr7ds
2024-10-19 21:30:26 [I] loader apply plugin nix:8epf22
2024-10-19 21:30:26 [I] loader apply plugin downloads:7trekn
2024-10-19 21:30:26 [I] assets missing config "selfUrl", fallback to "file:" scheme
2024-10-19 21:30:26 [I] nix nix plugin only works on linux
2024-10-19 21:30:26 [I] server server listening at http://127.0.0.1:5140
2024-10-19 21:30:26 [I] console webui is available at http://127.0.0.1:5140
2024-10-19 21:30:26 [I] adapter connect to server: ws://127.0.0.1:22333/
2024-10-19 21:30:26 [I] storeluna 同步上游: https://registry.koishi.chat/index.json
2024-10-19 21:30:27 [I] nix nix is not installed
2024-10-19 21:30:28 [I] storeluna 监听路径: /server/storeluna
2024-10-19 21:30:28 [I] canvas canvas started
2024-10-19 21:30:28 [I] ba-plugin 渲染模式:canvas
2024-10-19 21:30:28 [I] ba-plugin 🟡 正在更新json文件
2024-10-19 21:30:29 [I] ba-plugin ☁️🆕🟡云hash更新
2024-10-19 21:30:32 [E] ba-plugin TypeError: Cannot read properties of undefined (reading 'fname')
                            at file_random_survey (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7110:60)
                            at async initia (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7230:14)
                            at async auto_data_update_function (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7306:5)
                            at async Object.apply (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi-plugin-ba-plugin\lib\index.js:7310:5)
                            at async Promise.all (index 0)
                            at async Proxy.flush (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@cordisjs\core\lib\index.cjs:497:7)
                            at async Proxy.start (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@cordisjs\core\lib\index.cjs:571:5)
                            at async start (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\koishi\lib\worker\index.js:146:3)
2024-10-19 21:30:32 [I] ba-plugin 🟡本地资源检测未通过
2024-10-19 21:30:32 [I] ba-plugin ⬇️ 开始下载插件必须资源，请稍等哦（*＾-＾*）
2024-10-19 21:30:40 [I] ba-plugin 头像_1下载进度25%
2024-10-19 21:30:40 [I] ba-plugin 头像_1下载进度25%
2024-10-19 21:30:58 [I] ba-plugin 头像_1下载进度50%
2024-10-19 21:30:58 [I] ba-plugin 头像_1下载进度50%
2024-10-19 21:31:06 [I] ba-plugin 头像_1下载进度75%
2024-10-19 21:31:06 [I] ba-plugin 头像_1下载进度75%
2024-10-19 21:31:13 [I] ba-plugin 头像_1下载进度95%
2024-10-19 21:31:13 [I] ba-plugin 头像_1下载进度95%
2024-10-19 21:31:14 [I] ba-plugin ✔️（1/3）学生头像_1下载完毕
2024-10-19 21:31:21 [I] ba-plugin 头像_2下载进度25%
2024-10-19 21:31:21 [I] ba-plugin 头像_2下载进度25%
2024-10-19 21:31:27 [I] ba-plugin 头像_2下载进度50%
2024-10-19 21:31:27 [I] ba-plugin 头像_2下载进度50%
2024-10-19 21:31:28 [I] storeluna 同步成功: https://registry.koishi.chat/index.json
2024-10-19 21:31:33 [I] ba-plugin 头像_2下载进度75%
2024-10-19 21:31:33 [I] ba-plugin 头像_2下载进度75%
2024-10-19 21:31:38 [I] ba-plugin 头像_2下载进度95%
2024-10-19 21:31:38 [I] ba-plugin 头像_2下载进度95%
2024-10-19 21:31:39 [I] ba-plugin ✔️（2/3）学生头像_2下载完毕
2024-10-19 21:31:42 [I] ba-plugin 资源文件下载进度25%
2024-10-19 21:31:46 [I] ba-plugin 资源文件下载进度50%
2024-10-19 21:31:49 [I] ba-plugin 资源文件下载进度75%
2024-10-19 21:32:00 [I] ba-plugin 资源文件下载进度95%
2024-10-19 21:32:01 [I] ba-plugin ✔️（3/3）资源下载完毕
2024-10-19 21:32:06 [I] ba-plugin 🟢 json文件更新完毕
2024-10-19 21:32:06 [I] ba-plugin-get-active ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:32:06 [I] ba-plugin-get-active 🟢 总力获取加载完毕
2024-10-19 21:32:06 [I] ba-plugin-get-active 🟢 活动获取功能加载完毕
2024-10-19 21:32:06 [I] ba-plugin-guide ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:32:06 [I] ba-plugin-favorable 🟢 好感计算器加载完毕
2024-10-19 21:32:06 [I] ba-plugin-guide 🟢 攻略功能加载完毕
2024-10-19 21:32:06 [I] ba-plugin-gacha ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:32:06 [I] ba-plugin-gacha 🟢 抽卡模拟器加载完毕
2024-10-19 21:32:06 [I] ba-plugin-gacha 🟢 随机漫画加载完毕
```

我们发现可以稳定复现这样的bug

错误提示在index.js的7110行

**Comment by shangxueink** [comment]
发现报错在这里
```
      for (let i = 0; i < newhash.length; i++) {
        try {
          await fmp2.json_parse(`${root_json}/${oldjson[i].fname}`); // 这里报错
        } catch (e) {
          await fmp2.file_download(hashurl2, root_json, "hash.json");
          for (let i2 = 0; i2 < newhash.length; i2++) {
            await fmp2.file_download(`${jsonurl}${newhash[i2].fname}`, root_guide, `${newhash[i2].fname}`);
            await fmp2.file_download(`${jsonurl}${newhash[i2].fname}`, root_json, `${newhash[i2].fname}`);
          }
          log7.error(e);
          return status = false;
        }
      }
```

简单调试一下发现
```
      for (let i = 0; i < newhash.length; i++) {
        try {
          // 确保 oldjson[i] 存在且有 fname 属性
          if (!oldjson[i] || !oldjson[i].fname) {
            log7.error(`index ${i} : ${JSON.stringify(oldjson[i])}`);
            continue; // 跳过无效条目
          }
          await fmp2.json_parse(`${root_json}/${oldjson[i].fname}`);
        } catch (e) {
          await fmp2.file_download(hashurl2, root_json, "hash.json");
          for (let i2 = 0; i2 < newhash.length; i2++) {
            await fmp2.file_download(`${jsonurl}${newhash[i2].fname}`, root_guide, `${newhash[i2].fname}`);
            await fmp2.file_download(`${jsonurl}${newhash[i2].fname}`, root_json, `${newhash[i2].fname}`);
          }
          log7.error(e);
          return status = false;
        }
      }
```

```

2024-10-19 21:39:53 [I] ba-plugin 渲染模式:canvas
2024-10-19 21:39:53 [I] ba-plugin 🟡 正在更新json文件
2024-10-19 21:39:53 [I] ba-plugin ☁️🆕🟡云hash更新
2024-10-19 21:39:53 [E] ba-plugin index 11 : undefined
2024-10-19 21:39:56 [I] ba-plugin 🟢 json文件更新完毕
2024-10-19 21:39:56 [I] ba-plugin-get-active ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:39:56 [I] ba-plugin-get-active 🟢 总力获取加载完毕
2024-10-19 21:39:56 [I] ba-plugin-get-active 🟢 活动获取功能加载完毕
2024-10-19 21:39:56 [I] ba-plugin-guide ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:39:56 [I] ba-plugin-guide 🟢 攻略功能加载完毕
2024-10-19 21:39:56 [I] ba-plugin-favorable 🟢 好感计算器加载完毕
2024-10-19 21:39:56 [I] ba-plugin-gacha ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:39:56 [I] ba-plugin-gacha 🟢 抽卡模拟器加载完毕
2024-10-19 21:39:56 [I] ba-plugin-gacha 🟢 随机漫画加载完毕
```

**Comment by shangxueink** [comment]
我找到了data文件夹下的json文件，共有12个，去除一个hash.js，共11个
```
[favor_stu_tap.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/favor_stu_tap.json)	31.5 kB	2024/10/19 21:46:33
[favora_data.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/favora_data.json)	142 kB	2024/10/19 21:46:31
[gacha_data.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/gacha_data.json)	29.2 kB	2024/10/19 21:46:33
[hash.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/hash.json)	1.5 kB	2024/10/19 21:46:33
[khrtalk_satellite.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/khrtalk_satellite.json)	24.9 kB	2024/10/19 21:46:33
[liwu_list_rep.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/liwu_list_rep.json)	46.3 kB	2024/10/19 21:46:33
[manga_main.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/manga_main.json)	56.8 kB	2024/10/19 21:46:31
[map_guide_shangxue.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/map_guide_shangxue.json)	46.4 kB	2024/10/19 21:46:31
[sms_othersmatchlib.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/sms_othersmatchlib.json)	39.5 kB	2024/10/19 21:46:32
[sms_studata_main.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/sms_studata_main.json)	88.2 kB	2024/10/19 21:46:32
[sms_studata_toaro_stu.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/sms_studata_toaro_stu.json)	14.4 kB	2024/10/19 21:46:32
[sms_to_arona_data_revisions.json](https://github.com/D:/QQbots/QQ_bots/koishing/coding/koishi-app/data/bap-json/sms_to_arona_data_revisions.json)	1.3 kB	2024/10/19 21:46:32
```

**Comment by shangxueink** [comment]
然后我们发现代码里的循环是 `for (let i = 0; i < newhash.length; i++) {` 这个i在11的位置为undefined

是不是写错了

我们发现改成
```
for (let i = 0; i < newhash.length - 1; i++) {
```
就正常了
```
2024-10-19 21:46:29 [I] nix nix is not installed
2024-10-19 21:46:30 [I] canvas canvas started
2024-10-19 21:46:30 [I] ba-plugin 渲染模式:canvas
2024-10-19 21:46:30 [I] ba-plugin 🟡 正在更新json文件
2024-10-19 21:46:30 [I] storeluna 监听路径: /server/storeluna
2024-10-19 21:46:30 [I] ba-plugin ☁️🆕🟡云hash更新
2024-10-19 21:46:33 [I] ba-plugin 🟢 json文件更新完毕
2024-10-19 21:46:33 [I] ba-plugin-get-active ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:46:33 [I] ba-plugin-get-active 🟢 总力获取加载完毕
2024-10-19 21:46:33 [I] ba-plugin-get-active 🟢 活动获取功能加载完毕
2024-10-19 21:46:33 [I] ba-plugin-guide ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:46:33 [I] ba-plugin-guide 🟢 攻略功能加载完毕
2024-10-19 21:46:33 [I] ba-plugin-favorable 🟢 好感计算器加载完毕
2024-10-19 21:46:33 [I] ba-plugin-gacha ⚠️ md相关设置未完善,未启用MD模板
2024-10-19 21:46:33 [I] ba-plugin-gacha 🟢 抽卡模拟器加载完毕
2024-10-19 21:46:33 [I] ba-plugin-gacha 🟢 随机漫画加载完毕
```

**Comment by shangxueink** [comment]
这个 可能是因为 json文件更新，少了文件

或者是因为 作者 写差了咪

**Comment by Alin-sky** [comment]
云文件问题，已调整对象存储，未来还有机会再优化0
